### ISSUE TITLE
TDD Draft

### ISSUE THREAD

**Issue by m33k** [ekultails/cmd20py#2]
# Technical Design Document Draft
Before we start writing any code, two documents need to exist and explain all the details of the project. Both documents are known as TDDs. However, we will start with the Technical Design Document then move on to the Test Driven Developement document.

- This issue is being open to draft the technical design of cmd20py.

**Comment by m33k** [comment]
Hi @ekultails , The technical design document draft is being written in https://github.com/ekultails/cmd20py/wiki/Technical-Design-Document

**Comment by LukeShortCloud** [comment]
@m33k This is a great start, thanks for getting this going! I will add to this when I can.

Also to note, the technical design document will generally cover everything we need for the test driven development model/philosophy. Since we will have all of the expected methods, inputs, and outputs in the document we could then start development by using that as a base to create our unit and integration tests first.

**Comment by m33k** [comment]
@ekultails sounds good. It's been busy this past week so I haven't done anything as of late.

What section should we use to design and document the expected methods, inputs, and outputs?

Also I'll be leaning on you a bit to assist with the test driven development document as I have no experience with it. 

Thanks!

**Comment by m33k** [comment]
@ekultails Do you have any idea of what design patterns we might use? If you look in the wiki, there is a section called Design Patterns (section 2.4) 

Also if I remember correctly, we are adding a frontend to this application right?

**Comment by LukeShortCloud** [comment]
@m33k With the TDD design you provided, the methods should be documented in the `Application Architecture` section. My best guess as to what `Design Patterns` is is what methodologies will we be adopting to help build this (ex. test driven development).

[Here](https://github.com/ekultails/card_games_converter/blob/master/cgc_tdd.md) is a very simple technical design document I made for my last project. I like going with a full / more detailed TDD that you have started.

Yes, I think it would be good to add a front-end to this application. Both a web portal/dashboard and a standalone cross-platform GUI.

I will contribute to the design document before Friday. Then on Friday we can have our end-of-sprint sync.

**Comment by LukeShortCloud** [comment]
@m33k Okay, I think realistically we need to take a step back first. (1) We should confirm what technologies we want to use and then (2) create a "TDD" project on GitHub (to use as a kanban board) where we can break parts of the TDD up into a bunch of small SCRUM tasks we can assign. This should help give us better direction. We can figure this out during our upcoming sync.

A few personal things came up recently, taking up my time, but now I should be able to redirect time back into side projects.

**Comment by m33k** [comment]
Hi @ekultails, Sorry for the delay. I didn't know you made any changes to the wiki or commited a diagram. Although I'm watching the repo, no email alerts were sent about the changes. Nice work on the diagram. 

I added a few things to the remaining major sections. I'd like to finish the TDD draft before May 1st, 2019 so we can move forward. When you get a chance, could you review sections 4-7 and edit any details you'd like to add then we can close this issue.

**Comment by LukeShortCloud** [comment]
@m33k Acknowledged and agreed. I will review the TDD soon. We should sync up this Friday. I know the holidays have thrown us off track a bit.

**Comment by m33k** [comment]
@ekultails Perfect! OK Sounds good. Send the invite for 4pm-5pm. The holidays did throw us off track a bit, but the Jedi and the Padawan are back in action. lol

**Comment by LukeShortCloud** [comment]
Overall everything is looking good. There are some sections that needed, and still need, expansion on. We want there to have as much pre-planned out as possible. We can touch base on that tomorrow but we can definitely have this wrapped up this week.

Honestly, I am not a huge fan of the technical design document template we are using as some sections are vague with little explanation. I might take some extra time to take the information we have and re-write it into a more streamlined TDD that we would both understand. Development projects truly revolves around the TDD so having one that benefits us and gives us true clarity into what we are making is essential.

It is almost time to start getting into development work, my Padawan!

**Comment by m33k** [comment]
I agree. This TDD was made for a large company so it isn't designed for the type of project we are working on. We'll talk about it more during the sync up.

I can't wait for the development part! :smile:

**Comment by m33k** [comment]
Marking this issue as close since the TDD Draft is complete. We just have to maintain it going forward.
